language: python
python:
  - "2.7"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/project_tools/
script:
  - cwd=$(pwd)
  # run profile tool test
  - cd ${cwd}/src/
  - python profile_tool_test.py
  # run project tools test
  - cd ${cwd}/src/project_tools
  - python proj_test.py
